### ISSUE TITLE
Fix Livesness and Readiness Probes

### ISSUE THREAD

**Issue by fergmac** [bcgov/nr-gwells#100]
**Describe the task**
The probes are currently commented out due to failing during initial set up. They are likely failing due to the updated ports. 

This task includes the probes for the backend and frontend service. Also worth double checking the database service probes.

**Purpose**
Probes help to ensure that our services are healthy and ready to receive traffic.

**Acceptance Criteria**
- [x] Liveness and Readiness probes are successful for database service
- [ ] Liveness and Readiness probes are successful for backend service
- [ ] Liveness and Readiness probes are successful for frontend service

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by raarielgrace** [comment]
Database probes are already up.
