### ISSUE TITLE
Front-end console errors

### ISSUE THREAD

**Issue by fergmac** [bcgov/nr-gwells#119]
**Describe the task**
Currently when running the application there are Mapbox related errors appearing in the console. These need to be resolved to maintain the map functionality.

**Purpose**
We want to maintain the map functionality. 

**Acceptance Criteria**
- [ ] The application deploys to dev without console errors.

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by raarielgrace** [comment]
![Image](https://github.com/user-attachments/assets/c2c96787-b95e-44d2-9e89-ee8b2b45ab00)
`searchQueryParams` is included as a function in two different files that get imported together, so I'm changing the function names to be distinct.

**Comment by raarielgrace** [comment]
![Image](https://github.com/user-attachments/assets/706c2792-4f12-4477-a4bf-8292a7b54837)
The mapbox map is registering duplicate routes to the router, causing this issue. Easy to fix with a catch statement.

**Comment by raarielgrace** [comment]
![Image](https://github.com/user-attachments/assets/6ea54651-1343-4e3b-a65a-09bbe9a148f0)
We were accessing the Vue refs object incorrectly in one place.

**Comment by raarielgrace** [comment]
![Image](https://github.com/user-attachments/assets/ea02fef1-ae78-4227-837e-7580edd96172)
Warning based on one place where we don't conditionally check if `well.aquifer` is defined.
