### ISSUE TITLE
Determine best way to transfer issues from GWELLS to NR-GWELLS

### ISSUE THREAD

**Issue by Keegnan** [bcgov/nr-gwells#21]
**Description**
PO wants all issues in the same repo. There are no official ways to bulk transfer issues from repo to another. 

**Information we want to keep on each issues includes:**
- labels
- estimates
- description 
- comments

**Desired Outcome**
- Issues are copied, not transferred into NR-GWELLS with the above information included
- make any tickets required to do this/if really simple we can move forward with it

**Additional Context**
- If the only solution is to transfer and not copy we want to schedule it to the mark the event of transfer
- new repo are prefixed with "nr"

**Comment by lunamoonmoon** [comment]
Created a python script to copy issues from GWELLS and create them in NR-GWELLS. Comments and labels also get copied and both open and closed tickets are cloned.
https://github.com/lunamoonmoon/GitIssueCloner

**Comment by lunamoonmoon** [comment]
Python script works however will need to add to project after cloning. Can select all on issues page and add project > Sustainment Team
